### ISSUE TITLE
There is not a support for negative numbers?

### ISSUE THREAD

**Issue by pedrofsn** [MathBunny/newton-raphson#7]
It works:

Please input expression.
x*2
Please enter guess: 
10
Solution Found at: x= 0.0
Answer: 0.0

It isn't works:

Please input expression.
x*-2
Please enter guess: 
10
Exception in thread "main" java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at classes.PostfixEvaluater.evaluate(PostfixEvaluater.java:37)
	at classes.Operation.operate(Operation.java:21)
	at classes.Operation.compute(Operation.java:36)
	at classes.NewtonRaphsonConsole.compute(NewtonRaphsonConsole.java:29)
	at classes.NewtonRaphsonConsole.mainMenu(NewtonRaphsonConsole.java:79)
	at classes.NewtonRaphsonConsole.main(NewtonRaphsonConsole.java:14)

**Comment by MathBunny** [comment]
Did you try doing x*(-2)? Also is this in console mode or using the UI?

**Comment by pedrofsn** [comment]
I runned this function on visual version of this project:
> f(x) = (-3) + X

But I got the same error, so I think this probably not support negative numbers.

I've tried this too:
> f(x) = (10^(-2))*5+X
